name: omniedge
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-edge-mode:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install network tools
        run: |
          sudo apt-get -y update
          sudo apt-get install -y traceroute net-tools

      - name: OmniEdge Edge Mode
        uses: ./
        with:
          mode: edge
          network_id: ${{ secrets.OMNIEDGE_NETWORK_ID }}
          security_key: ${{ secrets.OMNIEDGE_SECURITY_KEY }}

      - name: Check connection
        run: |
          ps aux | grep omniedge
          ifconfig | grep inet
          traceroute ${{ secrets.OMNIEDGE_IP }}
